### ISSUE TITLE
zsh: command not found: findmy

### ISSUE THREAD

**Issue by GrandSlam90** [muehlt/home-assistant-findmy#15]
**Describe the bug**
Running 'findmy' from the command line after installation on Mac OS 14.0 Sonoma results in an 'zsh: command not found' error.

**To Reproduce**
1. Install using PIP3 as per instructions
2. Launch via 'findmy...' as shown
3. See error

**Expected behavior**
Application should launch

**Desktop (please complete the following information):**
 - OS: MacOS 14.0 Sonoma (clean install)

Happy to be told I've missed a step but I've tried both locally on this machine via Terminal and via a SSH session into the machine and both are giving the error.

**Comment by muehlt** [comment]
This is most likely a path issue related to your Python installation. A good fix depends on how you installed Python, but if you run `pip3 show home-assistant-findmy`, you should see a Location (probably a path ending with `site-packages`). Please try adding this location to your path.

(Add `export PATH=$PATH:/path/to/your/directory` to `~/.zshrc`, then run `source ~/.zshrc`)

**Comment by GrandSlam90** [comment]
Thanks for the quick reply.
I've checked the path and added it to my `~/.zshrc`. I now get `zsh: permission denied: findmy` which is strange as I'm the only user on the machine so I'm admin.
I've checked back and I ran `pip3 install home-assistant-findmy` as my normal user so I'm confused why I'm getting `permission denied`.

**Comment by GrandSlam90** [comment]
**RESOLVED**
I uninstalled and reinstalled. On reinstallation I got a message advising of the location and to add to `PATH`. This was a different location to the one reported by `pip3 show home-assistant-findmy'. Once corrected all works fine.
Thanks for the assistance.

**Comment by muehlt** [comment]
Ah, then you'd probably need to make the script executable as well, but at this point, it was the best decision to do a clean reinstall. Glad it works now. If you are having issues with special characters in device names, you can check out [this](https://github.com/muehlt/home-assistant-findmy/tree/fix/invalid_device_id) dev branch (or change device names) until I create a new release.
