### ISSUE TITLE
Home Assistant MQTT discovery or manual entries? Discussions relating to HA

### ISSUE THREAD

**Issue by DrSpaldo** [muehlt/home-assistant-findmy#3]
@muehlt, I just wanted to say that I've started using your script and it is great. I am running it in a MacOS VM on my Unraid machine and then the script in the terminal. I am getting most of my devices appearing natively in the MQTT section of Home Assistant. 

It is a little strange, I am getting 9 devices come through to the MQTT integration within Home Assistant, however, there are 15 devices that are appearing when I connect directly to the MQTT server via MQTT explorer. I am not sure why 6 devices are not making it into Home Assistant... 

I guess the reason for my post is to thank you and also to see if anyone else out there has created any MQTT sensors or device trackers via Home Assistant MQTT scripting/manual configuration? 

Is there a good place to find them, is it possible to have a discussion area within this Github?

**Comment by DrSpaldo** [comment]
I've also posted in the HA forms, to assist with people searching for the same issue:

https://community.home-assistant.io/t/is-there-any-way-to-track-apple-airtags-via-home-assistant/389049/34?u=drspaldo

**Comment by muehlt** [comment]
Hi, I'm glad you find the script helpful. I wrote it with a tight time budget and mainly needed it for an AirTag, so the functionality is not yet complete. However, I am a fan of early open-sourcing to improve things collaboratively. If you'd like to provide some logs or device attributes, I'm happy to look into it once I can.

**Comment by DrSpaldo** [comment]
Sure. What do you need exactly? and where should I send it?

**Comment by muehlt** [comment]
I'm sorry for not getting back to you sooner. Happy about any logs you have at hand, but attributes of the devices (i.e. what you see in the HA dev tool using the manual configuration) would be a good start too. Please just make sure to redact private information. If you don't want to post it here, you could reach out on Discord [[1]](https://discordapp.com/users/371380956755394576), or I'll create an email alias if that doesn't work for you. Thanks!

**Comment by muehlt** [comment]
@DrSpaldo, I believe you've already found a solution for your VM, but if you're open to testing it once more, I'd be keen to know if version 1.0.2 works well for you. One of the changes should significantly reduce the load on your instance, even with a 5s refresh time, which might solve the issue. Thanks for your patience!

You now can [install the package](https://github.com/muehlt/home-assistant-findmy/blob/main/.github/MIGRATION_GUIDE/1.0.2.md) using pip.

**Comment by DrSpaldo** [comment]
> @DrSpaldo, I believe you've already found a solution for your VM, but if you're open to testing it once more, I'd be keen to know if version 1.0.2 works well for you. One of the changes should significantly reduce the load on your instance, even with a 5s refresh time, which might solve the issue. Thanks for your patience!
> 
> You now can [install the package](https://github.com/muehlt/home-assistant-findmy/blob/main/.github/MIGRATION_GUIDE/1.0.2.md) using pip.

Hi @muehlt , sorry for the delay, have been doing other things. I will give this a go and let you know. The VM is kind of working but doesn't seem to update great. Let's hope your one works :)

**Comment by DrSpaldo** [comment]
I am having a few issues. I got it loaded using the normal user, it had the table with the items however, I wasn't getting anything coming through MQTT. Then I saw in the docs it said to run as root. So I reinstalled it with root, set the config options and now get an error saying it can't locate the Items.data file. There is more to type but may be some back & forward. I tried adding your discord user to my account but it says that I need the username not number?

**Comment by muehlt** [comment]
With the most recent version, you should be fine without root; sorry, I changed this in the guides but unfortunately left an artifact in the description that still mentions it (although it should still work fine if you locate files correctly). If you see the table of your devices already, you're good and probably encountering a different issue. May I ask what the names of your devices look like? If they contain special characters, your issue may be related to PR #13.

Regarding Discord, they recently changed their naming scheme for users, and everyone had to choose new names. You should be able to add me with the username `b_y_t_e`.

**Comment by muehlt** [comment]
You can now update to release [1.1.0](https://pypi.org/project/home-assistant-findmy/1.1.0/) by running `pip3 install --upgrade home-assistant-findmy`. If you didn't try to run PR #13 / #17 before, this might fix your issue. Otherwise please let me know on Discord and I'll also reopen the issue.
